name: Build and Deploy Frontend via FTP

on:
  push:
    branches:
      - main  # Exécute le workflow uniquement sur la branche principale

jobs:
  lint_and_build:
    runs-on: ubuntu-latest  # Utilisation d'une machine Ubuntu pour exécuter les étapes

    steps:
      # 1️⃣ Récupération du code source depuis le dépôt GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # 2️⃣ Installation de Node.js (version LTS recommandée)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'  # Utilise la dernière version stable (LTS)

      # 3️⃣ Installation des dépendances du projet
      - name: Install dependencies
        run: npm install

      # 4️⃣ Exécution du linting et du build en parallèle
      - name: Run Lint
        run: npm run lint
        continue-on-error: false  # Arrête si le lint échoue

      - name: Build Frontend
        run: npm run build
        continue-on-error: false  # Arrête si le build échoue

  deploy:
    needs: lint_and_build  # Déploie uniquement si le job `lint_and_build` réussit
    runs-on: ubuntu-latest

    steps:
      # 5️⃣ Déploiement sur le serveur FTP
      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}      # Adresse du serveur FTP
          username: ${{ secrets.FTP_USER }}    # Nom d'utilisateur FTP
          password: ${{ secrets.FTP_PASS }}    # Mot de passe FTP
          protocol: ftps                       # Utilisation de FTPS (plus sécurisé que FTP)
          port: 21                              # Port FTP par défaut
          local-dir: ./dist/                    # Répertoire local contenant le build (dossier généré par Vue)
          server-dir: www/frontend/dist/               # Répertoire distant où les fichiers seront déployés