name: Build and Deploy Frontend via FTP

on:
  push:
    branches:
      - main  # Exécute le workflow uniquement sur la branche principale

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build
        continue-on-error: false

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./dist  # Vérifie que le dossier `dist` existe bien


  deploy:
    runs-on: ubuntu-latest
    needs: [build,lint]  # Attend que `build` soit terminé avant de commencer

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./dist  # Assure que `dist` est au bon endroit

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}      # Adresse du serveur FTP
          username: ${{ secrets.FTP_USER }}    # Nom d'utilisateur FTP
          password: ${{ secrets.FTP_PASS }}    # Mot de passe FTP
          protocol: ftps                       # Utilisation de FTPS (plus sécurisé)
          port: 21                              # Port FTP par défaut
          local-dir: ./dist/                    # Le dossier build local
          server-dir: www/frontend/dist/        # Répertoire distant
